added documentation and fixed doxygen gh action

diff --git a/.github/actions/documentation/action.yml b/.github/actions/documentation/action.yml
--- a/.github/actions/documentation/action.yml
+++ b/.github/actions/documentation/action.yml
@@ -10,28 +10,31 @@ runs:
           # We only make check, not changes
           DOX_CONF_FILE=$(pwd)/Doxyfile
 
-          # ToDo: Add documentation about this command and describe better
+          # Append to DOX_CONF_FILE input source directories 
           {
               cat $DOX_CONF_FILE
               echo "INPUT" = $(pwd)/src $(pwd)/include $(pwd)/lib
           } > $DOX_CONF_FILE
 
           # Generate documentation
-          # ToDo: Add documentation about this command and describe better
+          # dot -c clears Graphviz configuration, doxygen uses Graphviz for generating graphical representations
           sudo dot -c
 
           ERROR_FILE_FLAG=$(pwd)/dox_errors.txt
 
-          # ToDo: Add documentation and describe better this command
-          DOXYGEN_COMMAND=$(doxygen -s $DOX_CONF_FILE) > $ERROR_FILE_FLAG
+          # create documentation: -s specifies comments of configurations items will be omitted.
+          # pipe stderr to error file
+          DOXYGEN_COMMAND=$(doxygen -s $DOX_CONF_FILE 2> $ERROR_FILE_FLAG)
 
+          # if error file not empty fail
           if [ -s $ERROR_FILE_FLAG ]; then
-              echo "Error: There are some files that are not documented correctly"
-              exit 1
+            echo "Error: There are some files that are not documented correctly"
+            exit 1
           else
-              echo "All files are documented correctly. Niiiceee"
-              exit 0
+            echo "All files are documented correctly. Niiiceee"
+            exit 0
           fi
+      
     # Upload errors as an artifact, when failed
     - uses: actions/upload-artifact@v3
       if: failure()
